### PR TITLE
Update JobTitle.md

### PR DESCRIPTION
**Pull request by DrOzturk**
I added reference to crosswalk from 3 to 3.1

### CODE REVIEW

**Review by gliu6 — COMMENTED** [review]
👍  I guess you just want to include the comparison excel file in the documentation

**Comment by DrOzturk** [comment]
yes added links to them.
Can you merge?
Thanks

**Comment by thomasmahoney** [comment]
@DrOzturk it actually looks a bit sloppy right now with the .md and .xlsx links for the first crosswalk butted up against each other. can you add newlines so it's a little more readable, and make the link texts more consistent?

**Comment by thomasmahoney** [comment]
friendlier link text might be like...
"Carotene V2.2 to V3 Crosswalk (table format)"
"Carotene V2.2 to V3 Crosswalk (Excel format)"

**Comment by thomasmahoney** [comment]
@DrOzturk looks better now, thank you. merging.

**Pull request merged**
